---

- name: Test if test_connection_report_host is set correctly
  ansible.builtin.assert:
    that:
      - test_connection_report_host is defined
      - test_connection_report_host is string
    quiet: yes

- name: Test if test_connection_report_directory is set correctly
  ansible.builtin.assert:
    that:
      - test_connection_report_directory is defined
      - test_connection_report_directory is string
    quiet: yes

- name: Test if test_connection_timeout is set correctly
  ansible.builtin.assert:
    that:
      - test_connection_timeout is defined
      - test_connection_timeout is number
      - test_connection_timeout >= 0
    quiet: yes
