---
# tasks file for test_connection

- name: import assert.yml
  ansible.builtin.import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: check if the ssh tcp port is open
  block:
    - name: wait for tcp port 22
      ansible.builtin.wait_for:
        port: 22
        host: "{{ ansible_ssh_host | default(ansible_host | default(inventory_hostname)) }}"
        connect_timeout: "{{ test_connection_timeout }}"
        timeout: "{{ test_connection_timeout }}"
      delegate_to: "{{ test_connection_report_host }}"
    - name: save results
      ansible.builtin.lineinfile:
        path: "{{ test_connection_report_directory }}/connection_succeeded.txt"
        line: "{{ ansible_ssh_host | default(ansible_host | default(inventory_hostname)) }}"
        create: yes
        mode: "0644"
      delegate_to: "{{ test_connection_report_host }}"
  rescue:
    - name: save results
      ansible.builtin.lineinfile:
        path: "{{ test_connection_report_directory }}/connection_failed.txt"
        line: "{{ ansible_ssh_host | default(ansible_host | default(inventory_hostname)) }}"
        create: yes
        mode: "0644"
      delegate_to: "{{ test_connection_report_host }}"

- name: check if a user can login
  block:
    - name: wait_for_connection
      ansible.builtin.wait_for_connection:
    - name: save results
      ansible.builtin.lineinfile:
        path: "{{ test_connection_report_directory }}/wait_for_connection_succeeded.txt"
        line: "{{ ansible_ssh_host | default(ansible_host | default(inventory_hostname)) }}"
        create: yes
        mode: "0644"
      delegate_to: "{{ test_connection_report_host }}"
  rescue:
    - name: save results
      ansible.builtin.lineinfile:
        path: "{{ test_connection_report_directory }}/wait_for_connection_failed.txt"
        line: "{{ ansible_ssh_host | default(ansible_host | default(inventory_hostname)) }}"
        create: yes
        mode: "0644"
      delegate_to: "{{ test_connection_report_host }}"

- name: check if become works
  block:
    - name: ping with become
      ansible.builtin.ping:
      become: yes
      become_user: root
    - name: save results
      ansible.builtin.lineinfile:
        path: "{{ test_connection_report_directory }}/become_succeeded.txt"
        line: "{{ ansible_ssh_host | default(ansible_host | default(inventory_hostname)) }}"
        create: yes
        mode: "0644"
      delegate_to: "{{ test_connection_report_host }}"
  rescue:
    - name: save results
      ansible.builtin.lineinfile:
        path: "{{ test_connection_report_directory }}/become_failed.txt"
        line: "{{ ansible_ssh_host | default(ansible_host | default(inventory_hostname)) }}"
        create: yes
        mode: "0644"
      delegate_to: "{{ test_connection_report_host }}"
